# Generated by Django 4.0.4 on 2022-05-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
