# Generated by Django 4.0.4 on 2022-05-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(),
        ),
    ]
